create DATABASE lifeline_hospital_analytics;
USE lifeline_hospital_analytics;
CREATE TABLE healthcare_data (
    Patient_ID INT,
    Admit_Date VARCHAR(20),
    Discharge_Date VARCHAR(20),
    Diagnosis VARCHAR(100),
    Bed_Occupancy VARCHAR(30),
    Test VARCHAR(100),
    Doctor_Name VARCHAR(100),
    Followup_Date VARCHAR(20),
    Feedback VARCHAR(30),
    Billing_Amount VARCHAR(20),
    Health_Insurance_Amount VARCHAR(20),
    Total_Amount_Payable VARCHAR(20)
);

#Q1: How many patients were admitted to the hospital?
CREATE VIEW total_patients AS
SELECT COUNT(*) AS Total_Patients
FROM healthcare_data;

# Result
SELECT * FROM total_patients;

 # Q2: What is the total hospital revenue?
 CREATE VIEW total_hospital_revenue AS
SELECT
    SUM(Billing_Amount_Clean) AS Total_Hospital_Revenue
FROM healthcare_data;

#Result
SELECT * FROM total_hospital_revenue;

# Q3: What is the average billing amount per patient?
CREATE VIEW average_billing_amount AS
SELECT
    ROUND(AVG(Billing_Amount_Clean),2) AS Average_Billing_Amount
FROM healthcare_data;

#Result
SELECT * FROM vw_average_billing_amount;

# Q4: What is the average length of stay of patients?
CREATE VIEW average_length_of_stay AS
SELECT
    ROUND(AVG(Length_of_Stay), 2) AS Average_Length_of_Stay
FROM healthcare_data;

#Result
SELECT * FROM average_length_of_stay;

# Q5: How many unique doctors treated patients?
CREATE VIEW total_doctors AS
SELECT
    COUNT(DISTINCT Doctor_Name) AS Total_Doctors
FROM healthcare_data;

#Result
SELECT * FROM vw_total_doctors;

# Q6: How many different diagnoses were treated?
CREATE VIEW total_diagnoses AS
SELECT
    COUNT(DISTINCT Diagnosis) AS Total_Diagnoses
FROM healthcare_data;

# Result
SELECT * FROM total_diagnoses;

# Q7: How many patients had a follow-up appointment versus no follow-up?
CREATE VIEW followup_status AS
SELECT
    CASE
        WHEN Followup_Date_Clean IS NULL THEN 'No Follow-up'
        ELSE 'Follow-up Scheduled'
    END AS Followup_Status,
    COUNT(*) AS Total_Patients
FROM healthcare_data
GROUP BY Followup_Status;

# Result
SELECT * FROM followup_status;

# Q8: Which are the Top 10 doctors by number of patients treated?
CREATE VIEW top10_doctors_by_patients AS
SELECT
    Doctor_Name,
    COUNT(*) AS Total_Patients
FROM healthcare_data
GROUP BY Doctor_Name
ORDER BY Total_Patients DESC
LIMIT 10;

# Result
SELECT * FROM top10_doctors_by_patients;
   
   # Q9: Which diagnosis is the most common?
   CREATE VIEW most_common_diagnosis AS
SELECT
    Diagnosis,
    COUNT(*) AS Total_Cases
FROM healthcare_data
GROUP BY Diagnosis
ORDER BY Total_Cases DESC;
   
   # Result
   SELECT * FROM most_common_diagnosis;
   
   # Q10: Which diagnosis generated the highest revenue?
   CREATE VIEW revenue_by_diagnosis AS
SELECT
    Diagnosis,
    SUM(Billing_Amount_Clean) AS Total_Revenue
FROM healthcare_data
GROUP BY Diagnosis
ORDER BY Total_Revenue DESC;
   
   # Result
   SELECT * FROM revenue_by_diagnosis;
   
   # Q11: Which medical test was performed most frequently?
   CREATE VIEW vw_test_frequency AS
SELECT
    Test,
    COUNT(*) AS Test_Count
FROM healthcare_data
GROUP BY Test
ORDER BY Test_Count DESC;
   
   # Result
   SELECT * FROM test_frequency;
   
   # Q12: What is the total revenue generated by each doctor?
   CREATE VIEW revenue_by_doctor AS
SELECT
    Doctor_Name,
    SUM(Billing_Amount_Clean) AS Total_Revenue
FROM healthcare_data
GROUP BY Doctor_Name
ORDER BY Total_Revenue DESC;

#Result
SELECT * FROM revenue_by_doctor;
   
   # Q13: What is the average billing amount for each diagnosis?
   CREATE VIEW avg_billing_by_diagnosis AS
SELECT
    Diagnosis,
    ROUND(AVG(Billing_Amount_Clean),2) AS Average_Billing
FROM healthcare_data
GROUP BY Diagnosis
ORDER BY Average_Billing DESC;
   
   #Result
   SELECT * FROM avg_billing_by_diagnosis;
   
   # Q14: Which bed occupancy type had the highest number of patients?
   CREATE VIEW bed_occupancy_analysis AS
SELECT
    Bed_Occupancy,
    COUNT(*) AS Total_Patients
FROM healthcare_data
GROUP BY Bed_Occupancy
ORDER BY Total_Patients DESC;
   
#Result
   SELECT * FROM bed_occupancy_analysis;

# Q15: Rank doctors based on total revenue generated.
CREATE VIEW doctor_revenue_rank AS
SELECT
    Doctor_Name,
    SUM(Billing_Amount_Clean) AS Total_Revenue,
    RANK() OVER (ORDER BY SUM(Billing_Amount_Clean) DESC) AS Revenue_Rank
FROM healthcare_data
GROUP BY Doctor_Name;

#Result
SELECT * FROM doctor_revenue_rank;

# Q16: Find the Top 10 highest billing patients.
CREATE VIEW top10_highest_billing_patients AS
SELECT
    Patient_ID,
    Doctor_Name,
    Diagnosis,
    Billing_Amount_Clean
FROM healthcare_data
ORDER BY Billing_Amount_Clean DESC
LIMIT 10;

#Result
SELECT * FROM top10_highest_billing_patients;

# Q17: Calculate monthly hospital revenue
CREATE VIEW monthly_revenue AS
SELECT
    DATE_FORMAT(Admit_Date_Clean,'%Y-%m') AS Month,
    SUM(Billing_Amount_Clean) AS Total_Revenue
FROM healthcare_data
GROUP BY Month
ORDER BY Month;

#Result
SELECT * FROM monthly_revenue;

# Q18: Calculate monthly patient admissions.
CREATE VIEW monthly_admissions AS
SELECT
    DATE_FORMAT(Admit_Date_Clean,'%Y-%m') AS Month,
    COUNT(*) AS Total_Admissions
FROM healthcare_data
GROUP BY Month
ORDER BY Month;

#Result
SELECT * FROM monthly_admissions;

# Q19: Calculate the insurance coverage percentage for each patient.
CREATE VIEW insurance_coverage_percentage AS
SELECT
    Patient_ID,
    Billing_Amount_Clean,
    Health_Insurance_Amount_Clean,
    ROUND((Health_Insurance_Amount_Clean / Billing_Amount_Clean) * 100,2) AS Insurance_Coverage_Percentage
FROM healthcare_data;

#Result
SELECT * FROM insurance_coverage_percentage;

# Q20: Which month generated the highest hospital revenue?
CREATE VIEW highest_revenue_month AS
SELECT
    DATE_FORMAT(Admit_Date_Clean,'%Y-%m') AS Month,
    SUM(Billing_Amount_Clean) AS Total_Revenue
FROM healthcare_data
GROUP BY Month
ORDER BY Total_Revenue DESC
LIMIT 1;

#Result
SELECT * FROM highest_revenue_month;

















